#!/usr/bin/env bash
# Displays DNS record information for subdomains of a given domain

# shellcheck disable=SC2086

get_dns_record() {
    local domain="$1"
    local subdomain="$2"

    dig "$subdomain.$domain" | awk '
        /ANSWER SECTION:/ {
            getline
            printf "The subdomain %s is a %s record and points to %s\n", "'"$subdomain"'", $4, $5
        }
    '
}

if [ $# -eq 1 ]; then
    get_dns_record "$1" "www"
    get_dns_record "$1" "lb-01"
    get_dns_record "$1" "web-01"
    get_dns_record "$1" "web-02"
else
    get_dns_record "$1" "$2"
fi
